#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# ghqをfzfにパクパクさせる
fgh() {
  cd "$(ghq root)/$(ghq list >/dev/null | fzf)"
}
# tab+j
zle -N fgh
bindkey '^I[' fgh

# 履歴検索
function select-history() {
  BUFFER=$(history -n -r 1 | fzf --no-sort +m --query "$LBUFFER" --prompt="History > ")
  CURSOR=$#BUFFER
}
# tab+h
zle -N select-history
bindkey '^Ih' select-history
